map_num_long: 3
map_num_wide: 3
non_fly_list: []
map_pre_dict: {'(0,0)': [],'(0,1)': ['E'],'(0,2)': [],'(1,0)': ['N'],'(1,1)': ['N','E','S','W'],'(1,2)': ['S','E'],'(2,0)': [],'(2,1)': ['W'],'(2,2)': ['W']}