map_num_long: 2
map_num_wide: 6
non_fly_list: []
map_pre_dict: {'(0,0)':['N','E'], '(0,1)':['S','N','E'], '(0,2)':['S','N'], '(0,3)':['E','N','S'], '(0,4)':['S','N'], '(0,5)':['S','E'], '(1,0)':['W'], '(1,1)':['W','N'],'(1,2)':['S'], '(1,3)':['W'], '(1,4)':[], '(1,5)':['W']}